/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.cxcore;
import com.sun.jna.Structure;
/**
 * <i>native declaration : modules/core/include/opencv2/core/core_c.h:3122</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphScanner extends Structure {
	/**
	 * current graph vertex (or current edge origin)<br>
	 * C type : CvGraphVtx*
	 */
	public sj.opencv.jna.cxcore.CvGraphVtx.ByReference vtx;
	/**
	 * current graph edge destination vertex<br>
	 * C type : CvGraphVtx*
	 */
	public sj.opencv.jna.cxcore.CvGraphVtx.ByReference dst;
	/**
	 * current edge<br>
	 * C type : CvGraphEdge*
	 */
	public sj.opencv.jna.cxcore.CvGraphEdge.ByReference edge;
	/**
	 * the graph<br>
	 * C type : CvGraph*
	 */
	public sj.opencv.jna.cxcore.CvGraph.ByReference graph;
	/**
	 * the graph vertex stack<br>
	 * C type : CvSeq*
	 */
	public sj.opencv.jna.cxcore.CvSeq.ByReference stack;
	/// the lower bound of certainly visited vertices
	public int index;
	/// event mask
	public int mask;
	public CvGraphScanner() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"vtx", "dst", "edge", "graph", "stack", "index", "mask"});
	}
	/**
	 * @param vtx current graph vertex (or current edge origin)<br>
	 * C type : CvGraphVtx*<br>
	 * @param dst current graph edge destination vertex<br>
	 * C type : CvGraphVtx*<br>
	 * @param edge current edge<br>
	 * C type : CvGraphEdge*<br>
	 * @param graph the graph<br>
	 * C type : CvGraph*<br>
	 * @param stack the graph vertex stack<br>
	 * C type : CvSeq*<br>
	 * @param index the lower bound of certainly visited vertices<br>
	 * @param mask event mask
	 */
	public CvGraphScanner(sj.opencv.jna.cxcore.CvGraphVtx.ByReference vtx, sj.opencv.jna.cxcore.CvGraphVtx.ByReference dst, sj.opencv.jna.cxcore.CvGraphEdge.ByReference edge, sj.opencv.jna.cxcore.CvGraph.ByReference graph, sj.opencv.jna.cxcore.CvSeq.ByReference stack, int index, int mask) {
		super();
		this.vtx = vtx;
		this.dst = dst;
		this.edge = edge;
		this.graph = graph;
		this.stack = stack;
		this.index = index;
		this.mask = mask;
		initFieldOrder();
	}
	public static class ByReference extends CvGraphScanner implements Structure.ByReference {
		
	};
	public static class ByValue extends CvGraphScanner implements Structure.ByValue {
		
	};
}
