/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.cxcore;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
/**
 * <i>native declaration : modules/core/include/opencv2/core/types_c.h:1520</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSparseMat extends Structure {
	public int type;
	public int dims;
	/// C type : int*
	public IntByReference refcount;
	public int hdr_refcount;
	/// C type : CvSet*
	public sj.opencv.jna.cxcore.CvSet.ByReference heap;
	/// C type : void**
	public PointerByReference hashtable;
	public int hashsize;
	public int valoffset;
	public int idxoffset;
	/// C type : int[32]
	public int[] size = new int[32];
	public CvSparseMat() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"type", "dims", "refcount", "hdr_refcount", "heap", "hashtable", "hashsize", "valoffset", "idxoffset", "size"});
	}
	public static class ByReference extends CvSparseMat implements Structure.ByReference {
		
	};
	public static class ByValue extends CvSparseMat implements Structure.ByValue {
		
	};
}
