/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.imgproc;
import com.sun.jna.Structure;
/**
 * <i>native declaration : modules/imgproc/include/opencv2/imgproc/types_c.h:3984</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvConvexityDefect extends Structure {
	/**
	 * point of the contour where the defect begins<br>
	 * C type : CvPoint*
	 */
	public sj.opencv.jna.cxcore.CvPoint.ByReference start;
	/**
	 * point of the contour where the defect ends<br>
	 * C type : CvPoint*
	 */
	public sj.opencv.jna.cxcore.CvPoint.ByReference end;
	/**
	 * the farthest from the convex hull point within the defect<br>
	 * C type : CvPoint*
	 */
	public sj.opencv.jna.cxcore.CvPoint.ByReference depth_point;
	/// distance between the farthest point and the convex hull
	public float depth;
	public CvConvexityDefect() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"start", "end", "depth_point", "depth"});
	}
	/**
	 * @param start point of the contour where the defect begins<br>
	 * C type : CvPoint*<br>
	 * @param end point of the contour where the defect ends<br>
	 * C type : CvPoint*<br>
	 * @param depth_point the farthest from the convex hull point within the defect<br>
	 * C type : CvPoint*<br>
	 * @param depth distance between the farthest point and the convex hull
	 */
	public CvConvexityDefect(sj.opencv.jna.cxcore.CvPoint.ByReference start, sj.opencv.jna.cxcore.CvPoint.ByReference end, sj.opencv.jna.cxcore.CvPoint.ByReference depth_point, float depth) {
		super();
		this.start = start;
		this.end = end;
		this.depth_point = depth_point;
		this.depth = depth;
		initFieldOrder();
	}
	public static class ByReference extends CvConvexityDefect implements Structure.ByReference {
		
	};
	public static class ByValue extends CvConvexityDefect implements Structure.ByValue {
		
	};
}
