/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.imgproc;
import com.sun.jna.Structure;
/**
 * <i>native declaration : modules/imgproc/include/opencv2/imgproc/types_c.h:3853</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMoments extends Structure {
	/// spatial moments
	public double m00;
	/// spatial moments
	public double m10;
	/// spatial moments
	public double m01;
	/// spatial moments
	public double m20;
	/// spatial moments
	public double m11;
	/// spatial moments
	public double m02;
	/// spatial moments
	public double m30;
	/// spatial moments
	public double m21;
	/// spatial moments
	public double m12;
	/// spatial moments
	public double m03;
	/// central moments
	public double mu20;
	/// central moments
	public double mu11;
	/// central moments
	public double mu02;
	/// central moments
	public double mu30;
	/// central moments
	public double mu21;
	/// central moments
	public double mu12;
	/// central moments
	public double mu03;
	/// m00 != 0 ? 1/sqrt(m00) : 0
	public double inv_sqrt_m00;
	public CvMoments() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"m00", "m10", "m01", "m20", "m11", "m02", "m30", "m21", "m12", "m03", "mu20", "mu11", "mu02", "mu30", "mu21", "mu12", "mu03", "inv_sqrt_m00"});
	}
	public static class ByReference extends CvMoments implements Structure.ByReference {
		
	};
	public static class ByValue extends CvMoments implements Structure.ByValue {
		
	};
}
