/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.imgproc;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import sj.opencv.jna.cxcore.CvPoint;
/**
 * <i>native declaration : modules/imgproc/include/opencv2/imgproc/types_c.h:3909</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvChainPtReader extends Structure {
	public int header_size;
	/// C type : CvSeq*
	public sj.opencv.jna.cxcore.CvSeq.ByReference seq;
	/// C type : CvSeqBlock*
	public sj.opencv.jna.cxcore.CvSeqBlock.ByReference block;
	/// C type : schar*
	public Pointer ptr;
	/// C type : schar*
	public Pointer block_min;
	/// C type : schar*
	public Pointer block_max;
	public int delta_index;
	/// C type : schar*
	public Pointer prev_elem;
	public byte code;
	/// C type : CvPoint
	public CvPoint pt;
	/// C type : schar[8][2]
	public byte[] deltas = new byte[(8) * (2)];
	public CvChainPtReader() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"header_size", "seq", "block", "ptr", "block_min", "block_max", "delta_index", "prev_elem", "code", "pt", "deltas"});
	}
	public static class ByReference extends CvChainPtReader implements Structure.ByReference {
		
	};
	public static class ByValue extends CvChainPtReader implements Structure.ByValue {
		
	};
}
