/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.imgproc;
import com.sun.jna.Structure;
/**
 * <i>native declaration : modules/imgproc/include/opencv2/imgproc/types_c.h:3863</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvHuMoments extends Structure {
	/// Hu invariants
	public double hu1;
	/// Hu invariants
	public double hu2;
	/// Hu invariants
	public double hu3;
	/// Hu invariants
	public double hu4;
	/// Hu invariants
	public double hu5;
	/// Hu invariants
	public double hu6;
	/// Hu invariants
	public double hu7;
	public CvHuMoments() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"hu1", "hu2", "hu3", "hu4", "hu5", "hu6", "hu7"});
	}
	/**
	 * @param hu1 Hu invariants<br>
	 * @param hu2 Hu invariants<br>
	 * @param hu3 Hu invariants<br>
	 * @param hu4 Hu invariants<br>
	 * @param hu5 Hu invariants<br>
	 * @param hu6 Hu invariants<br>
	 * @param hu7 Hu invariants
	 */
	public CvHuMoments(double hu1, double hu2, double hu3, double hu4, double hu5, double hu6, double hu7) {
		super();
		this.hu1 = hu1;
		this.hu2 = hu2;
		this.hu3 = hu3;
		this.hu4 = hu4;
		this.hu5 = hu5;
		this.hu6 = hu6;
		this.hu7 = hu7;
		initFieldOrder();
	}
	public static class ByReference extends CvHuMoments implements Structure.ByReference {
		
	};
	public static class ByValue extends CvHuMoments implements Structure.ByValue {
		
	};
}
