/* Description and License
 * A Java library that wraps the functionality of the native image 
 * processing library OpenCV
 *
 * (c) Sigurdur Orn Adalgeirsson (siggi@alum.mit.edu)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */
 
package sj.opencv.jna.cxcore;
import com.sun.jna.Union;
/**
 * <i>native declaration : modules/core/include/opencv2/core/types_c.h:1265</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Cv64suf extends Union {
	/// C type : int64
	public long i;
	/// C type : uint64
	public long u;
	public double f;
	public Cv64suf() {
		super();
	}
	public Cv64suf(double f) {
		super();
		this.f = f;
		setType(Double.TYPE);
	}
	/// @param i_or_u C type : int64, or C type : uint64
	public Cv64suf(long i_or_u) {
		super();
		this.u = this.i = i_or_u;
		setType(Long.TYPE);
	}
	public static class ByReference extends Cv64suf implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends Cv64suf implements com.sun.jna.Structure.ByValue {
		
	};
}
